import './globals.css'
import {Inter, Poppins} from 'next/font/google'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (

     <>
         <Header />
         <main>
             {children}
         </main>
         <Footer />
     </>







  )
}
